fix: extra_vars type in RunnerConfig
ansible/ansible-runner pull request #422
Opened 2020-03-06 12:00 UTC by mnecas

There was issue with extra_vars that they were passing only string values.
This fix will allow return lists and booleans etc.

2020-03-06 13:01 UTC, mwperina approved these changes
+1

2020-03-06 14:08 UTC, mnecas commented
Hi, @matburt,
could you please take a look at this PR?

2020-03-09 13:01 UTC, matburt requested changes
Just a few comments:

Rewrite the commits to be fewer in number and more accurately describe the change that's occurring and why.

Also, rather than changing the tests to cover just this use case, add the original tests back in and write new tests to cover the new data type(s).

2020-03-09 16:40 UTC, matburt approved these changes

2020-03-09 16:52 UTC, merged