Keep worker --private-data-dir when --delete not given
ansible/ansible-runner pull request #887
Opened 2021-10-25 20:37 UTC by AlanCoding

I messed up our requirements a little bit with https://github.com/ansible/ansible-runner/pull/820, and now I'm getting reports that people _want_ the private_data_dir to be kept on the node running the `ansible-runner worker` command, and it is (unwantedly) getting deleted at the end of the run.

If you look at how I wrote the docs, I was dodgy about this case. I wrote it so that it would get cleaned up if it was a _new_ directory. That didn't even work for the AWX use case, for which there is an intent to respect the setting `AWX_CLEANUP_PATHS` on both control and worker nodes.

I will take out of draft when I have confirmed this works with a production install.

2021-10-25 20:46 UTC, AlanCoding commented
I think I have verified this sufficiently for myself now.

2021-10-26 15:21 UTC, Shrews approved these changes
LGTM. Make sure this is backported to the appropriate version(s).

2021-10-26 15:52 UTC, samdoran requested changes

2021-10-26 15:52 UTC, samdoran commented on docs/remote_jobs.rst
> +unless you give the `--delete` flag, in which case the directory will be deleted both before and after the run.
RST uses double backticks for inline code formatting. I clarified the wording a bit, if I'm understanding the behavior correctly.
```suggestion
If the ``--private-data-dir`` option is given, then the directory will persist after the run finishes
unless the ``--delete`` flag is also set. In that case, the private data directory will be deleted before execution if it exists and also removed after execution.
```

2021-10-26 15:52 UTC, samdoran commented on ansible_runner/__main__.py
> +            cleanup_folder(project_path)
Is `cleanup_folder` providing more functionality here than `shutil.rmtree(project_path, ignore_errors=True`? There are a couple of places where we use the return value, but not here.

2021-10-26 15:52 UTC, samdoran commented on ansible_runner/__main__.py
> +            cleanup_folder(env_path)
Same comment as above.

2021-10-26 15:52 UTC, samdoran commented on ansible_runner/__main__.py
> +        elif not vargs.get('private_data_dir'):
For clarity, store the values. This would be a great place to use an assignment expression (`:=`) but I don't think we're ready to make Python 3.8 a hard requirement yet.
```suggestion
        private_data_dir = vargs.get('private_data_dir')
        delete_directory = vargs.get('delete_directory', False)
        if private_data_dir and delete_directory:
            shutil.rmtree(private_data_dir, True)
            register_for_cleanup(private_data_dir)removed?
        elif private_data_dir is None:
```

2021-10-26 15:52 UTC, samdoran commented on ansible_runner/__main__.py
> +        elif not vargs.get('private_data_dir'):
I'm not sure about the call to `register_for_cleanup()` after removing the directory. Does it get recreated and this is to ensure the directory is removed before it is later created? It's probably worth putting a comment in here explaining the reason behind the code.

2021-10-26 15:52 UTC, samdoran commented on test/integration/test_transmit_worker_process.py
> +@pytest.mark.parametrize('delete', [False, True])
This should be broken into separate tests to avoid the use of conditional asserts, making the tests easier to read:
- no `--private-data-dir` or `--delete`
- only `--private-data-dir`
- both `--private-data-dir` and `--delete`

We should also have unit tests to make sure `shutil`, `register_for_cleanup`, and `cleanup_folder` are called as expected.

2021-10-26 17:02 UTC, AlanCoding commented on docs/remote_jobs.rst
> +unless you give the `--delete` flag, in which case the directory will be deleted both before and after the run.
looks great, the only thing I might add is putting () around (if it exists) to help readability

2021-10-26 17:03 UTC, AlanCoding commented on ansible_runner/__main__.py
> +            cleanup_folder(project_path)
that's true, I didn't know to use `ignore_errors=True`

2021-10-26 17:07 UTC, AlanCoding commented on ansible_runner/__main__.py
> +        elif not vargs.get('private_data_dir'):
These two lines track with what was said in the docs. If the directory exists before the run, it deletes it, and it also deletes it after the run. So, deletion before and after. The run will _always_ create the directory, because ansible-runner works via a private data dir.

2021-10-26 17:19 UTC, AlanCoding commented on test/integration/test_transmit_worker_process.py
> +@pytest.mark.parametrize('delete', [False, True])
I could see the argument for re-organizing the parametrize. But there's a lot of different directions I could take your feedback in, and I don't want to create a bunch of redundant test content. So I'll try what makes sense to me and go from there.

2021-10-27 14:02 UTC, samdoran commented on test/integration/test_transmit_worker_process.py
> +@pytest.mark.parametrize('delete', [False, True])
Would you mind if I added tests to this PR?

2021-10-27 14:02 UTC, samdoran commented
Docs build failure is unrelated to this PR (see #888).

2021-10-27 14:16 UTC, AlanCoding commented on test/integration/test_transmit_worker_process.py
> +@pytest.mark.parametrize('delete', [False, True])
no problem at all.

2021-11-01 17:39 UTC, samdoran commented
Sorry I haven't made any progress here. I've been trying to fix the docs build all last week and am fighting CI issues this morning. This PR will need to be rebased once the docs build fixes land since RTD does not do speculative merges when running tests.

2021-11-01 17:49 UTC, AlanCoding commented
Are the aforementioned fixes for the docs build https://github.com/ansible/ansible-runner/pull/894?

2021-11-01 17:53 UTC, samdoran commented
Yes.

2021-11-01 17:54 UTC, samdoran commented
Looks like we are having CI infrastructure issues, so I'm not sure when we be able to get changes merged.

2021-11-05 17:35 UTC, samdoran commented
I added the tests we needed. If all goes well, we can merge this.

2021-11-05 17:35 UTC, samdoran approved these changes

2021-11-05 19:54 UTC, AlanCoding commented
Looks good to me :+1: thanks!

2021-11-08 15:01 UTC, AlanCoding commented
I'm fine to squash all commits, but I don't know what's really going on with the bot.

2021-11-08 15:06 UTC, merged